name: Deploy External API to Salesforce

on:
  # Automatically triggers when there is a push to the main branch
  push:
    branches:
      - master
  # Optionally, allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  create-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run : |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir ~/sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C ~/sfdx-cli --strip-components 1
          echo "$HOME/sfdx-cli/bin" >> $GITHUB_PATH 
          sfdx --version
      

      - name: Authenticate with Salesforce 
        run: |
         echo "${{secrets.SF_AUTH_URL}}"> authfile.txt
         sfdx auth:sfdxurl:store -f authfile.txt --set-default-dev-hub

      - name: Create a New Package Version
        run: |
         PACKAGE_ID="0HogK0000000001SAA"
         sfdx force:package:version:create -p $PACKAGE_ID --installation-key-bypass -w 10 --json | tee package.json