name: Deploy External API to Salesforce

on:
  # Automatically triggers when there is a push to the main branch
  push:
    branches:
      - main
  # Optionally, allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core

      # Step 3: Authenticate to Salesforce using GitHub Secrets
      - name: Authenticate to Salesforce Org
        run: |
          sfdx force:auth:login --username ${{ secrets.SALESFORCE_USERNAME }} --password ${{ secrets.SALESFORCE_PASSWORD }}  --setdefaultusername

      # Step 4: Run Apex tests before deployment
      - name: Run Apex Tests
        run: |
          result=$(sfdx force:apex:test:run --resultformat human --codecoverage --synchronous --wait 10)
          echo "$result"

          if [[ "$result" == *"Test failed"* ]]; then
            echo "Apex tests failed. Aborting deployment."
            exit 1
          fi
          echo "Apex tests passed."
      
      # Step 5: Deploy the External API module to Salesforce Org
      - name: Deploy Metadata to Salesforce Org
        run: |
          sfdx force:source:deploy --sourcepath ./src/external-api --targetusername ${{ secrets.SALESFORCE_USERNAME }} --json --loglevel debug

    